package sofa

import (
	"fmt"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

// The files in testdata/sofar/ are small synthetic SOFA files written by
// sofar (pyfar) through netCDF-C, a writer independent of go-sofa's. They are
// committed (MIT, generated by scripts/make_sofar_fixtures.py) so that CI
// covers the conventions whose real example files only sofacoustics.org
// hosts. The pinned values are the ones the generator wrote (rounded to six
// decimals, so float64 comparisons are exact).

// sofarFixture opens testdata/sofar/name. The files are committed, so a
// missing file is a failure, never a skip.
func sofarFixture(t *testing.T, name string) *File {
	t.Helper()
	p := filepath.Join("testdata", "sofar", name)
	f, err := Open(p)
	if err != nil {
		t.Fatalf("Open(%s): %v", p, err)
	}
	return f
}

// sofarHeader is what every fixture is checked for.
type sofarHeader struct {
	convention, version, dataType string
	m, r, e, n                    int
}

func checkSofarHeader(t *testing.T, f *File, want sofarHeader) {
	t.Helper()
	got := sofarHeader{f.SOFAConventions, f.SOFAConventionsVersion, f.DataType, f.M, f.R, f.E, f.N}
	if got != want {
		t.Fatalf("header = %+v, want %+v", got, want)
	}
	if f.APIName != "sofar SOFA API for Python (pyfar.org)" {
		t.Errorf("APIName = %q, want sofar", f.APIName)
	}
	if f.DateCreated != "2026-09-26 12:00:00" || f.DateModified != "2026-09-26 12:00:00" {
		t.Errorf("DateCreated/DateModified = %q/%q, want the generator's fixed date", f.DateCreated, f.DateModified)
	}
	if !strings.HasPrefix(f.License, "MIT") {
		t.Errorf("License = %q, want MIT", f.License)
	}
}

func checkFloat(t *testing.T, name string, got, want float64) {
	t.Helper()
	if got != want {
		t.Errorf("%s = %.17g, want %.17g", name, got, want)
	}
}

func checkVectors(t *testing.T, name string, got, want []Vector3) {
	t.Helper()
	if !reflect.DeepEqual(got, want) {
		t.Errorf("%s = %v, want %v", name, got, want)
	}
}

func checkType(t *testing.T, name, got, want string) {
	t.Helper()
	if !strings.EqualFold(got, want) {
		t.Errorf("%s Type = %q, want %q", name, got, want)
	}
}

func TestSofarGeneralTF(t *testing.T) {
	f := sofarFixture(t, "GeneralTF_2.0.sofa")
	checkSofarHeader(t, f, sofarHeader{"GeneralTF", "2.0", DataTypeTF, 4, 4, 1, 8})
	if want := []float64{125, 250, 500, 1000, 2000, 4000, 8000, 16000}; !reflect.DeepEqual(f.Frequencies, want) {
		t.Errorf("Frequencies = %v, want %v", f.Frequencies, want)
	}
	checkFloat(t, "Data.Real[0][0][0]", f.TFReal[0][0][0], 0.345584)
	checkFloat(t, "Data.Real[2][1][5]", f.TFReal[2][1][5], -1.481818)
	checkFloat(t, "Data.Real[3][3][7]", f.TFReal[3][3][7], 0.588969)
	checkFloat(t, "Data.Imag[0][0][0]", f.TFImag[0][0][0], -0.840722)
	checkFloat(t, "Data.Imag[3][3][7]", f.TFImag[3][3][7], -0.4699)
	checkType(t, "SourcePosition", f.SourcePositionType, CoordinateSpherical)
	checkVectors(t, "SourcePositions", f.SourcePositions,
		[]Vector3{{0, 0, 1.5}, {90, 0, 1.5}, {180, 0, 1.5}, {270, 30, 1.5}})
	checkVectors(t, "ReceiverPositions", f.ReceiverPositions,
		[]Vector3{{0, 0.09, 0}, {0, -0.09, 0}, {0.05, 0, 0}, {-0.05, 0, 0}})
	if f.IsSHEncoded() {
		t.Error("IsSHEncoded() = true for a TF file")
	}
}

func TestSofarGeneralTFE(t *testing.T) {
	f := sofarFixture(t, "GeneralTF-E_1.0.sofa")
	checkSofarHeader(t, f, sofarHeader{"GeneralTF-E", "1.0", DataTypeTFE, 4, 2, 3, 6})
	if want := []float64{100, 200, 400, 800, 1600, 3200}; !reflect.DeepEqual(f.Frequencies, want) {
		t.Errorf("Frequencies = %v, want %v", f.Frequencies, want)
	}
	// sofar stores Data.Real [M,R,N,E]; go-sofa exposes [M][R][E][N].
	checkFloat(t, "Data.Real[0][0][0][0]", f.TFRealE[0][0][0][0], 0.189053)
	checkFloat(t, "Data.Real m1 r1 n4 e2", f.TFRealE[1][1][2][4], 1.198671)
	checkFloat(t, "Data.Real m3 r1 n5 e2", f.TFRealE[3][1][2][5], 0.353289)
	checkFloat(t, "Data.Imag[0][0][0][0]", f.TFImagE[0][0][0][0], -1.561824)
	checkFloat(t, "Data.Imag m3 r1 n5 e2", f.TFImagE[3][1][2][5], -1.067177)
	checkType(t, "EmitterPosition", f.EmitterPositionType, CoordinateCartesian)
	checkVectors(t, "EmitterPositions", f.EmitterPositions, []Vector3{{0, 0, 0}, {0.1, 0, 0}, {0, 0.1, 0}})
	checkVectors(t, "SourcePositions", f.SourcePositions,
		[]Vector3{{0, 0, 2}, {45, 0, 2}, {90, 10, 2}, {135, -10, 2}})
	if f.IsSHEncoded() {
		t.Error("IsSHEncoded() = true for cartesian emitters")
	}
}

func TestSofarFreeFieldHRTF(t *testing.T) {
	f := sofarFixture(t, "FreeFieldHRTF_1.0.sofa")
	checkSofarHeader(t, f, sofarHeader{"FreeFieldHRTF", "1.0", DataTypeTFE, 3, 2, 1, 5})
	checkFloat(t, "Data.Real[0][0][0][0]", f.TFRealE[0][0][0][0], 2.040919)
	checkFloat(t, "Data.Real m1 r0 n2", f.TFRealE[1][0][0][2], -0.281287)
	checkFloat(t, "Data.Real m2 r1 n4", f.TFRealE[2][1][0][4], 1.002314)
	checkFloat(t, "Data.Imag m2 r1 n4", f.TFImagE[2][1][0][4], 0.491368)
	checkType(t, "SourcePosition", f.SourcePositionType, CoordinateSpherical)
	checkVectors(t, "SourcePositions", f.SourcePositions, []Vector3{{0, 0, 1.2}, {120, 0, 1.2}, {240, 45, 1.2}})
	checkVectors(t, "ReceiverPositions", f.ReceiverPositions, []Vector3{{0, 0.09, 0}, {0, -0.09, 0}})
	if f.IsSHEncoded() {
		t.Error("IsSHEncoded() = true for EmitterPosition:Type cartesian")
	}
}

func TestSofarFreeFieldHRTFSH(t *testing.T) {
	f := sofarFixture(t, "FreeFieldHRTF_1.0_SH_L2.sofa")
	checkSofarHeader(t, f, sofarHeader{"FreeFieldHRTF", "1.0", DataTypeTFE, 1, 2, 9, 4})
	checkType(t, "EmitterPosition", f.EmitterPositionType, CoordinateSphericalHarmonics)
	if !f.IsSHEncoded() {
		t.Fatal("IsSHEncoded() = false")
	}
	if l, ok := f.SHOrder(); !ok || l != 2 {
		t.Errorf("SHOrder() = %d, %v, want 2, true", l, ok)
	}
	if n := f.SHCoefficientCount(); n != 9 {
		t.Errorf("SHCoefficientCount() = %d, want 9", n)
	}
	if w := f.SHWarnings(); len(w) != 0 {
		t.Errorf("SHWarnings() = %v, want none", w)
	}
	if len(f.EmitterPositions) != 9 {
		t.Errorf("len(EmitterPositions) = %d, want 9", len(f.EmitterPositions))
	}
	checkFloat(t, "Data.Real[0][0][0][0]", f.TFRealE[0][0][0][0], -0.651791)
	checkFloat(t, "Data.Real r1 n3 e8", f.TFRealE[0][1][8][3], -0.136445)
	checkFloat(t, "Data.Imag r0 n2 e4", f.TFImagE[0][0][4][2], 1.250697)
	checkFloat(t, "Data.Imag r1 n3 e8", f.TFImagE[0][1][8][3], -0.054842)
	checkVectors(t, "SourcePositions", f.SourcePositions, []Vector3{{0, 0, 1}})
}

func TestSofarSimpleFreeFieldHRSOS(t *testing.T) {
	f := sofarFixture(t, "SimpleFreeFieldHRSOS_1.0.sofa")
	checkSofarHeader(t, f, sofarHeader{"SimpleFreeFieldHRSOS", "1.0", DataTypeSOS, 6, 2, 1, 12})
	if sr, err := f.SamplingRateScalar(); err != nil || sr != 44100 {
		t.Errorf("SamplingRateScalar() = %g, %v, want 44100", sr, err)
	}
	checkFloat(t, "Data.SOS[0][0][0]", f.SOSCoefficients[0][0][0], 0.549005)
	checkFloat(t, "Data.SOS[2][0][4]", f.SOSCoefficients[2][0][4], -0.237815)
	checkFloat(t, "Data.SOS[5][1][11]", f.SOSCoefficients[5][1][11], 0.793725)
	for m := range f.M {
		for r := range f.R {
			if a0, a0b := f.SOSCoefficients[m][r][3], f.SOSCoefficients[m][r][9]; a0 != 1 || a0b != 1 {
				t.Fatalf("a0 of m=%d r=%d = %g, %g, want 1, 1", m, r, a0, a0b)
			}
		}
	}
	want := make([]Vector3, 6)
	for i := range want {
		want[i] = Vector3{float64(60 * i), 0, 1}
	}
	checkVectors(t, "SourcePositions", f.SourcePositions, want)
	if d, err := f.DelayAt(5, 1); err != nil || d != 0 {
		t.Errorf("DelayAt(5, 1) = %g, %v, want 0", d, err)
	}
}

func TestSofarSingleRoomSRIR(t *testing.T) {
	f := sofarFixture(t, "SingleRoomSRIR_1.0.sofa")
	checkSofarHeader(t, f, sofarHeader{"SingleRoomSRIR", "1.0", DataTypeFIR, 3, 4, 1, 64})
	if !f.IsSRIR() || f.IsBRIR() {
		t.Errorf("IsSRIR() = %v, IsBRIR() = %v, want true, false", f.IsSRIR(), f.IsBRIR())
	}
	if order, ok := f.AmbisonicsOrder(); !ok || order != 1 {
		t.Errorf("AmbisonicsOrder() = %d, %v, want 1, true", order, ok)
	}
	checkFloat(t, "RoomVolume", f.RoomVolume, 120.5)
	checkFloat(t, "RoomTemperature", f.RoomTemperature, 293.15)
	if f.RoomType != "shoebox" {
		t.Errorf("RoomType = %q, want shoebox", f.RoomType)
	}
	if w := f.ConventionWarnings(); len(w) != 0 {
		t.Errorf("ConventionWarnings() = %v, want none", w)
	}
	checkFloat(t, "Data.IR[0][0][0]", f.ImpulseResponses[0][0][0], 1.053116)
	checkFloat(t, "Data.IR[1][2][10]", f.ImpulseResponses[1][2][10], -0.462228)
	checkFloat(t, "Data.IR[2][3][63]", f.ImpulseResponses[2][3][63], 0.027037)
	if sr, err := f.SamplingRateScalar(); err != nil || sr != 48000 {
		t.Errorf("SamplingRateScalar() = %g, %v, want 48000", sr, err)
	}
	checkVectors(t, "ListenerPositions", f.ListenerPositions,
		[]Vector3{{2, 3, 1.2}, {2.5, 3, 1.2}, {3, 3, 1.2}})
	checkVectors(t, "SourcePositions", f.SourcePositions,
		[]Vector3{{5, 1, 1.5}, {5, 1, 1.5}, {5, 1, 1.5}})
	checkType(t, "ReceiverPosition", f.ReceiverPositionType, CoordinateSpherical)
	for _, name := range []string{"ReceiverDescriptions", "ReceiverView", "MeasurementDate", "RoomCornerA"} {
		if !hasVariable(f, name) {
			t.Errorf("variable %s not kept in Variables", name)
		}
	}
	// Known loss (PLAN.md E7): go-hdf5 lists 29 of the file's 30 root links
	// and misses ReceiverUp, so Open silently cannot keep it. When this
	// fails, go-hdf5 is fixed: assert hasVariable instead.
	if hasVariable(f, "ReceiverUp") {
		t.Error("ReceiverUp is now read: go-hdf5 E7 is fixed, update this test and KNOWN_LOST in scripts/interop_check.py")
	}
}

func TestSofarSingleRoomDRIR(t *testing.T) {
	f := sofarFixture(t, "SingleRoomDRIR_0.3.sofa")
	checkSofarHeader(t, f, sofarHeader{"SingleRoomDRIR", "0.3", DataTypeFIR, 2, 2, 1, 48})
	if !f.IsBRIR() || f.IsSRIR() {
		t.Errorf("IsBRIR() = %v, IsSRIR() = %v, want true, false", f.IsBRIR(), f.IsSRIR())
	}
	if f.RoomType != "reverberant" {
		t.Errorf("RoomType = %q, want reverberant", f.RoomType)
	}
	if f.ListenerView != (Vector3{0, 1, 0}) || f.ListenerUp != (Vector3{0, 0, 1}) {
		t.Errorf("ListenerView/Up = %v/%v, want {0 1 0}/{0 0 1}", f.ListenerView, f.ListenerUp)
	}
	checkFloat(t, "Data.IR[0][0][0]", f.ImpulseResponses[0][0][0], 0.00123)
	checkFloat(t, "Data.IR[0][1][3]", f.ImpulseResponses[0][1][3], -0.934007)
	checkFloat(t, "Data.IR[1][1][47]", f.ImpulseResponses[1][1][47], 0.018903)
	checkVectors(t, "ListenerPositions", f.ListenerPositions, []Vector3{{1, 2, 1.5}})
	checkVectors(t, "SourcePositions", f.SourcePositions, []Vector3{{3, 4, 1.5}, {0, 4, 1.5}})
	if d, err := f.Duration(); err != nil || d != 0.001 {
		t.Errorf("Duration() = %g, %v, want 0.001", d, err)
	}
}

func hasVariable(f *File, name string) bool {
	for _, v := range f.Variables {
		if v.Name == name {
			return true
		}
	}
	return false
}

// sofarSaveKnownFailures maps fixtures that go-sofa cannot save yet to the
// error it returns. SingleRoomSRIR has 33 root links (26 variables and 7
// dimensions), more than go-hdf5's fixed 256-byte root local heap holds
// (PLAN.md E6). When go-hdf5 is fixed this test fails: delete the entry.
var sofarSaveKnownFailures = map[string]string{
	"SingleRoomSRIR_1.0.sofa": "local heap is full",
}

// TestSofarFixturesRoundTrip saves every sofar fixture with go-sofa and
// checks that reopening yields the same File: nothing sofar wrote is lost or
// changed by Open → Save → Open, except the documented defaults Save adds
// for a missing ListenerView/ListenerUp.
func TestSofarFixturesRoundTrip(t *testing.T) {
	names, err := filepath.Glob(filepath.Join("testdata", "sofar", "*.sofa"))
	if err != nil {
		t.Fatal(err)
	}
	if len(names) != 7 {
		t.Fatalf("found %d files in testdata/sofar, want 7: %v", len(names), names)
	}
	for _, p := range names {
		name := filepath.Base(p)
		t.Run(name, func(t *testing.T) {
			src := sofarFixture(t, name)
			if len(src.Dropped) != 0 {
				t.Errorf("Open dropped %v", src.Dropped)
			}
			out := filepath.Join(t.TempDir(), name)
			err := src.Save(out)
			if known, ok := sofarSaveKnownFailures[name]; ok {
				if err == nil || !strings.Contains(err.Error(), known) {
					t.Fatalf("Save: %v, want the known failure %q (fixed? remove it from sofarSaveKnownFailures)", err, known)
				}
				// Without the variables go-sofa does not model, the file
				// has few enough root links to save.
				src.Variables = nil
				err = src.Save(out)
			}
			if err != nil {
				t.Fatalf("Save: %v", err)
			}
			back, err := Open(out)
			if err != nil {
				t.Fatalf("reopen: %v", err)
			}
			if want := withSaveDefaults(src); !reflect.DeepEqual(back, want) {
				t.Errorf("round trip changed the file:\n%s", strings.Join(fileFieldDiff(back, want), "\n"))
			}
		})
	}
}

// withSaveDefaults returns a copy of f with the values Save writes for an
// unset ListenerView/ListenerUp and their coordinate system.
func withSaveDefaults(f *File) *File {
	g := *f
	if g.ListenerView == (Vector3{}) {
		g.ListenerView = Vector3{X: 1}
	}
	if g.ListenerUp == (Vector3{}) {
		g.ListenerUp = Vector3{Z: 1}
	}
	if g.ListenerViewType == "" {
		g.ListenerViewType, g.ListenerViewUnits = f.listenerViewCoordinates()
	}
	return &g
}

// fileFieldDiff lists the File fields, exported or not, whose printed values
// differ (%#v prints floats exactly).
func fileFieldDiff(got, want *File) []string {
	var out []string
	g, w := reflect.ValueOf(got).Elem(), reflect.ValueOf(want).Elem()
	for i := range g.NumField() {
		if gf, wf := g.Field(i), w.Field(i); fmt.Sprintf("%#v", gf) != fmt.Sprintf("%#v", wf) {
			out = append(out, fmt.Sprintf("  %s: got %v, want %v", g.Type().Field(i).Name, gf, wf))
		}
	}
	return out
}
